# Makefile.in generated by automake 1.6.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = .

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/GENtle
pkglibdir = $(libdir)/GENtle
pkgincludedir = $(includedir)/GENtle
top_builddir = .

ACLOCAL = ${SHELL} /Users/magnusmanske/wx/wxWidgets/build-release/mine/GENtle/missing --run aclocal-1.6
AUTOCONF = ${SHELL} /Users/magnusmanske/wx/wxWidgets/build-release/mine/GENtle/missing --run autoconf
AUTOMAKE = ${SHELL} /Users/magnusmanske/wx/wxWidgets/build-release/mine/GENtle/missing --run automake-1.6
AUTOHEADER = ${SHELL} /Users/magnusmanske/wx/wxWidgets/build-release/mine/GENtle/missing --run autoheader

am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :

EXEEXT = 
OBJEXT = o
PATH_SEPARATOR = :
AMTAR = ${SHELL} /Users/magnusmanske/wx/wxWidgets/build-release/mine/GENtle/missing --run tar
AWK = awk
CC = gcc
CXX = g++
DEPDIR = .deps
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
PACKAGE = GENtle
STRIP = 
VERSION = 1.5
WX_LIBS =              -framework QuickTime -framework IOKit -framework Carbon -framework Cocoa -framework System  -lwx_macud-2.5 
am__include = include
am__quote = 
install_sh = /Users/magnusmanske/wx/wxWidgets/build-release/mine/GENtle/install-sh
SUFFIXES = .cpp .rc

bin_PROGRAMS = GENtle

EXTRA_DIST = mondrian.xpm \
variables.csv \
blank.db \
default.tab \
bitmaps/align.bmp \
bitmaps/cocktail.bmp \
bitmaps/display_features.bmp \
bitmaps/helpcs.bmp \
bitmaps/new.xpm \
bitmaps/plasmid_linear.bmp \
bitmaps/print.xpm \
bitmaps/settings_tool.bmp \
bitmaps/alignment.bmp \
bitmaps/copy.bmp \
bitmaps/display_restriction.bmp \
bitmaps/help.xpm \
bitmaps/open.bmp \
bitmaps/preview.bmp \
bitmaps/project.bmp \
bitmaps/splash.bmp \
bitmaps/align_tool.bmp \
bitmaps/copy.xpm \
bitmaps/draft.xbm \
bitmaps/image.bmp \
bitmaps/open.xpm \
bitmaps/preview.xpm \
bitmaps/protein.bmp \
bitmaps/tick.bmp \
bitmaps/bitmap1.bmp \
bitmaps/cut.bmp \
bitmaps/drawing.xbm\
bitmaps/mode_both.bmp \
bitmaps/orfs.bmp \
bitmaps/primer.bmp \
bitmaps/redo.bmp \
bitmaps/undo.bmp \
bitmaps/bitmap2.bmp \
bitmaps/cut.xpm       \
bitmaps/flowchar.xbm \
bitmaps/mode_edit.bmp \
bitmaps/paste.bmp \
bitmaps/primer_export.bmp \
bitmaps/save.bmp \
bitmaps/web.bmp \
bitmaps/calc.bmp \
bitmaps/Helix.bmp \
bitmaps/mode_view.bmp \
bitmaps/paste.xpm \
bitmaps/primer_import.bmp \
bitmaps/save.xpm \
bitmaps/write.xbm\
bitmaps/calc_tool.bmp \
bitmaps/dirplain.xbm \
bitmaps/help.bmp \
bitmaps/new.bmp \
bitmaps/plasmid_circular.bmp \
bitmaps/print.bmp \
bitmaps/scissors.bmp


GENtle_LDADD = $(WX_LIBS) -L/usr/lib -lsqlite -lsqlite3 -lmysqlclient
GENtle_LDFLAGS = -s
GENtle_SOURCES = TXMLfile.cpp\
TVectorTree.cpp\
TVirtualGel.cpp\
TVectorEditorItems.cpp\
TVectorEditorEnzymes.cpp\
TVectorEditor.cpp\
TVector.cpp\
TUndo.cpp\
TUReadSeq.cpp\
TStorage.cpp\
TSilmutDialog.cpp\
TRestrictionEditor.cpp\
TPrimer.cpp\
TPrimerDialog.cpp\
TPDB.cpp\
TLigationDialog.cpp\
TMainTree.cpp\
todo.cpp\
TItemEditDialog.cpp\
TImageDisplay.cpp\
TIMGreader.cpp\
TextImportDialog.cpp\
TClone.cpp\
SequenceTypes.cpp\
TCalculator.cpp\
SequenceTypeRestriction.cpp\
SequenceTypePlot.cpp\
SequenceTypeFeature.cpp\
SequenceTypeDNA.cpp\
SequenceTypeAlign.cpp\
SequenceTypeABI.cpp\
SequenceTypeAA.cpp\
SequenceCanvas.cpp\
SendHTTP.cpp\
RestrictionEnzymes.cpp\
ProgramOptionsDialog.cpp\
PlasmidCanvasLinear.cpp\
PrimerDesign.cpp\
PlasmidCanvasHandlers.cpp\
PlasmidCanvasCircular.cpp\
PlasmidCanvas.cpp\
MyFrame.cpp\
MyChild.cpp\
MiscDialogs.cpp\
ManageDatabase.cpp\
main.cpp\
GenBank.cpp\
FindSequenceDialog.cpp\
ExternalNCBI.cpp\
ExternalInterface.cpp\
ExternalBLAST.cpp\
ChildBase.cpp\
CoolCanvas.cpp\
AminoAcids.cpp\
Alignment.cpp\
ABIviewer.cpp\
ABItype.cpp\
TAlignmentDialog.cpp\
AutoAnnotate.cpp\
TGraph.cpp\
TGraphDisplay.cpp\
TGraphScale.cpp\
CGview.cpp\
ureadseq.c\
ncoils.cpp\
TPhylip.cpp\
TPhyloTree.cpp\
tinyxml/tinyxmlparser.cpp\
tinyxml/tinyxmlerror.cpp\
tinyxml/tinyxml.cpp\
tinyxml/tinystr.cpp\
clustalw/alnscore.cpp\
clustalw/amenu.cpp\
clustalw/calcgap.cpp\
clustalw/calcprf1.cpp\
clustalw/calcprf2.cpp\
clustalw/calctree.cpp\
clustalw/clustalw.cpp\
clustalw/gcgcheck.cpp\
clustalw/interfac.cpp\
clustalw/malign.cpp\
clustalw/palign.cpp\
clustalw/prfalign.cpp\
clustalw/random.cpp\
clustalw/readmat.cpp\
clustalw/sequence.cpp\
clustalw/showpair.cpp\
clustalw/trees.cpp\
clustalw/util.cpp\
ipc/element.cpp\
ipc/gp_out.cpp\
ipc/ipc.cpp\
ipc/pars.cpp\
enums.h \
lin_sqlite.h \
lin_sqlite3.h \
TXMLfile.h\
AutoAnnotate.h\
CGview.h\
TAlignmentDialog.h\
TGraph.h\
TVectorTree.h\
TVirtualGel.h\
TVectorEditor.h\
TVector.h\
TUndo.h\
TUReadSeq.h\
TStorage.h\
TSilmutDialog.h\
TRestrictionEditor.h\
TPrimer.h\
TPrimerDialog.h\
TPDB.h\
TLigationDialog.h\
TMainTree.h\
TItemEditDialog.h\
TImageDisplay.h\
TIMGreader.h\
TextImportDialog.h\
TClone.h\
TCalculator.h\
SequenceCanvas.h\
SendHTTP.h\
RestrictionEnzymes.h\
ProgramOptionsDialog.h\
PrimerDesign.h\
PlasmidCanvas.h\
MyFrame.h\
MyChild.h\
MiscDialogs.h\
ManageDatabase.h\
main.h\
GenBank.h\
FindSequenceDialog.h\
ExternalInterface.h\
ChildBase.h\
CoolCanvas.h\
AminoAcids.h\
Alignment.h\
ABIviewer.h\
ABItype.h\
ureadseq.h\
TPhylip.h\
TPhyloTree.h\
ncoils.h\
tinyxml/tinyxml.h\
tinyxml/tinystr.h\
clustalw/clustalw.h\
clustalw/dayhoff.h \
clustalw/general.h \
clustalw/matrices.h \
clustalw/param.h \
clustalw/xmenu.h\
ipc/element.h\
ipc/global.h\
ipc/gp_out.h\
ipc/ipc.h\
ipc/parse.h

subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES =
bin_PROGRAMS = GENtle$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

am_GENtle_OBJECTS = TXMLfile.$(OBJEXT) TVectorTree.$(OBJEXT) \
	TVirtualGel.$(OBJEXT) TVectorEditorItems.$(OBJEXT) \
	TVectorEditorEnzymes.$(OBJEXT) TVectorEditor.$(OBJEXT) \
	TVector.$(OBJEXT) TUndo.$(OBJEXT) TUReadSeq.$(OBJEXT) \
	TStorage.$(OBJEXT) TSilmutDialog.$(OBJEXT) \
	TRestrictionEditor.$(OBJEXT) TPrimer.$(OBJEXT) \
	TPrimerDialog.$(OBJEXT) TPDB.$(OBJEXT) \
	TLigationDialog.$(OBJEXT) TMainTree.$(OBJEXT) todo.$(OBJEXT) \
	TItemEditDialog.$(OBJEXT) TImageDisplay.$(OBJEXT) \
	TIMGreader.$(OBJEXT) TextImportDialog.$(OBJEXT) \
	TClone.$(OBJEXT) SequenceTypes.$(OBJEXT) TCalculator.$(OBJEXT) \
	SequenceTypeRestriction.$(OBJEXT) SequenceTypePlot.$(OBJEXT) \
	SequenceTypeFeature.$(OBJEXT) SequenceTypeDNA.$(OBJEXT) \
	SequenceTypeAlign.$(OBJEXT) SequenceTypeABI.$(OBJEXT) \
	SequenceTypeAA.$(OBJEXT) SequenceCanvas.$(OBJEXT) \
	SendHTTP.$(OBJEXT) RestrictionEnzymes.$(OBJEXT) \
	ProgramOptionsDialog.$(OBJEXT) PlasmidCanvasLinear.$(OBJEXT) \
	PrimerDesign.$(OBJEXT) PlasmidCanvasHandlers.$(OBJEXT) \
	PlasmidCanvasCircular.$(OBJEXT) PlasmidCanvas.$(OBJEXT) \
	MyFrame.$(OBJEXT) MyChild.$(OBJEXT) MiscDialogs.$(OBJEXT) \
	ManageDatabase.$(OBJEXT) main.$(OBJEXT) GenBank.$(OBJEXT) \
	FindSequenceDialog.$(OBJEXT) ExternalNCBI.$(OBJEXT) \
	ExternalInterface.$(OBJEXT) ExternalBLAST.$(OBJEXT) \
	ChildBase.$(OBJEXT) CoolCanvas.$(OBJEXT) AminoAcids.$(OBJEXT) \
	Alignment.$(OBJEXT) ABIviewer.$(OBJEXT) ABItype.$(OBJEXT) \
	TAlignmentDialog.$(OBJEXT) AutoAnnotate.$(OBJEXT) \
	TGraph.$(OBJEXT) TGraphDisplay.$(OBJEXT) TGraphScale.$(OBJEXT) \
	CGview.$(OBJEXT) ureadseq.$(OBJEXT) ncoils.$(OBJEXT) \
	TPhylip.$(OBJEXT) TPhyloTree.$(OBJEXT) tinyxmlparser.$(OBJEXT) \
	tinyxmlerror.$(OBJEXT) tinyxml.$(OBJEXT) tinystr.$(OBJEXT) \
	alnscore.$(OBJEXT) amenu.$(OBJEXT) calcgap.$(OBJEXT) \
	calcprf1.$(OBJEXT) calcprf2.$(OBJEXT) calctree.$(OBJEXT) \
	clustalw.$(OBJEXT) gcgcheck.$(OBJEXT) interfac.$(OBJEXT) \
	malign.$(OBJEXT) palign.$(OBJEXT) prfalign.$(OBJEXT) \
	random.$(OBJEXT) readmat.$(OBJEXT) sequence.$(OBJEXT) \
	showpair.$(OBJEXT) trees.$(OBJEXT) util.$(OBJEXT) \
	element.$(OBJEXT) gp_out.$(OBJEXT) ipc.$(OBJEXT) pars.$(OBJEXT)
GENtle_OBJECTS = $(am_GENtle_OBJECTS)
GENtle_DEPENDENCIES =

DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"GENtle\" -DVERSION=\"1.5\" 
DEFAULT_INCLUDES =  -I. -I$(srcdir)
CPPFLAGS =  -I/usr/lib/wx/include/mac-unicode-debug-2.5 -I/usr/include/wx-2.5 -D__WXDEBUG__ -D__WXMAC__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DNO_GCC_PRAGMA
LDFLAGS = 
LIBS = 
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
DEP_FILES = ./$(DEPDIR)/ABItype.Po ./$(DEPDIR)/ABIviewer.Po \
	./$(DEPDIR)/Alignment.Po ./$(DEPDIR)/AminoAcids.Po \
	./$(DEPDIR)/AutoAnnotate.Po ./$(DEPDIR)/CGview.Po \
	./$(DEPDIR)/ChildBase.Po ./$(DEPDIR)/CoolCanvas.Po \
	./$(DEPDIR)/ExternalBLAST.Po \
	./$(DEPDIR)/ExternalInterface.Po \
	./$(DEPDIR)/ExternalNCBI.Po \
	./$(DEPDIR)/FindSequenceDialog.Po \
	./$(DEPDIR)/GenBank.Po \
	./$(DEPDIR)/ManageDatabase.Po \
	./$(DEPDIR)/MiscDialogs.Po ./$(DEPDIR)/MyChild.Po \
	./$(DEPDIR)/MyFrame.Po ./$(DEPDIR)/PlasmidCanvas.Po \
	./$(DEPDIR)/PlasmidCanvasCircular.Po \
	./$(DEPDIR)/PlasmidCanvasHandlers.Po \
	./$(DEPDIR)/PlasmidCanvasLinear.Po \
	./$(DEPDIR)/PrimerDesign.Po \
	./$(DEPDIR)/ProgramOptionsDialog.Po \
	./$(DEPDIR)/RestrictionEnzymes.Po \
	./$(DEPDIR)/SendHTTP.Po \
	./$(DEPDIR)/SequenceCanvas.Po \
	./$(DEPDIR)/SequenceTypeAA.Po \
	./$(DEPDIR)/SequenceTypeABI.Po \
	./$(DEPDIR)/SequenceTypeAlign.Po \
	./$(DEPDIR)/SequenceTypeDNA.Po \
	./$(DEPDIR)/SequenceTypeFeature.Po \
	./$(DEPDIR)/SequenceTypePlot.Po \
	./$(DEPDIR)/SequenceTypeRestriction.Po \
	./$(DEPDIR)/SequenceTypes.Po \
	./$(DEPDIR)/TAlignmentDialog.Po \
	./$(DEPDIR)/TCalculator.Po ./$(DEPDIR)/TClone.Po \
	./$(DEPDIR)/TGraph.Po ./$(DEPDIR)/TGraphDisplay.Po \
	./$(DEPDIR)/TGraphScale.Po \
	./$(DEPDIR)/TIMGreader.Po \
	./$(DEPDIR)/TImageDisplay.Po \
	./$(DEPDIR)/TItemEditDialog.Po \
	./$(DEPDIR)/TLigationDialog.Po \
	./$(DEPDIR)/TMainTree.Po ./$(DEPDIR)/TPDB.Po \
	./$(DEPDIR)/TPhylip.Po ./$(DEPDIR)/TPhyloTree.Po \
	./$(DEPDIR)/TPrimer.Po ./$(DEPDIR)/TPrimerDialog.Po \
	./$(DEPDIR)/TRestrictionEditor.Po \
	./$(DEPDIR)/TSilmutDialog.Po \
	./$(DEPDIR)/TStorage.Po ./$(DEPDIR)/TUReadSeq.Po \
	./$(DEPDIR)/TUndo.Po ./$(DEPDIR)/TVector.Po \
	./$(DEPDIR)/TVectorEditor.Po \
	./$(DEPDIR)/TVectorEditorEnzymes.Po \
	./$(DEPDIR)/TVectorEditorItems.Po \
	./$(DEPDIR)/TVectorTree.Po \
	./$(DEPDIR)/TVirtualGel.Po ./$(DEPDIR)/TXMLfile.Po \
	./$(DEPDIR)/TextImportDialog.Po \
	./$(DEPDIR)/alnscore.Po ./$(DEPDIR)/amenu.Po \
	./$(DEPDIR)/calcgap.Po ./$(DEPDIR)/calcprf1.Po \
	./$(DEPDIR)/calcprf2.Po ./$(DEPDIR)/calctree.Po \
	./$(DEPDIR)/clustalw.Po ./$(DEPDIR)/element.Po \
	./$(DEPDIR)/gcgcheck.Po ./$(DEPDIR)/gp_out.Po \
	./$(DEPDIR)/interfac.Po ./$(DEPDIR)/ipc.Po \
	./$(DEPDIR)/main.Po ./$(DEPDIR)/malign.Po \
	./$(DEPDIR)/ncoils.Po ./$(DEPDIR)/palign.Po \
	./$(DEPDIR)/pars.Po ./$(DEPDIR)/prfalign.Po \
	./$(DEPDIR)/random.Po ./$(DEPDIR)/readmat.Po \
	./$(DEPDIR)/sequence.Po ./$(DEPDIR)/showpair.Po \
	./$(DEPDIR)/tinystr.Po ./$(DEPDIR)/tinyxml.Po \
	./$(DEPDIR)/tinyxmlerror.Po \
	./$(DEPDIR)/tinyxmlparser.Po ./$(DEPDIR)/todo.Po \
	./$(DEPDIR)/trees.Po ./$(DEPDIR)/ureadseq.Po \
	./$(DEPDIR)/util.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -g -O2
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
CXXFLAGS = -g -O2 -I/usr/lib/wx/include/mac-unicode-debug-2.5 -I/usr/include/wx-2.5 -D__WXDEBUG__ -D__WXMAC__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -DNO_GCC_PRAGMA
DIST_SOURCES = $(GENtle_SOURCES)
DIST_COMMON = README AUTHORS COPYING ChangeLog INSTALL Makefile.am \
	Makefile.in NEWS aclocal.m4 configure configure.in depcomp \
	install-sh missing
SOURCES = $(GENtle_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .rc .c .o .obj

am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)

$(top_builddir)/config.status: $(srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck
$(srcdir)/configure:  $(srcdir)/configure.in $(ACLOCAL_M4) $(CONFIGURE_DEPENDENCIES)
	cd $(srcdir) && $(AUTOCONF)

$(ACLOCAL_M4):  configure.in 
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
tinyxmlparser.$(OBJEXT): tinyxml/tinyxmlparser.cpp
tinyxmlerror.$(OBJEXT): tinyxml/tinyxmlerror.cpp
tinyxml.$(OBJEXT): tinyxml/tinyxml.cpp
tinystr.$(OBJEXT): tinyxml/tinystr.cpp
alnscore.$(OBJEXT): clustalw/alnscore.cpp
amenu.$(OBJEXT): clustalw/amenu.cpp
calcgap.$(OBJEXT): clustalw/calcgap.cpp
calcprf1.$(OBJEXT): clustalw/calcprf1.cpp
calcprf2.$(OBJEXT): clustalw/calcprf2.cpp
calctree.$(OBJEXT): clustalw/calctree.cpp
clustalw.$(OBJEXT): clustalw/clustalw.cpp
gcgcheck.$(OBJEXT): clustalw/gcgcheck.cpp
interfac.$(OBJEXT): clustalw/interfac.cpp
malign.$(OBJEXT): clustalw/malign.cpp
palign.$(OBJEXT): clustalw/palign.cpp
prfalign.$(OBJEXT): clustalw/prfalign.cpp
random.$(OBJEXT): clustalw/random.cpp
readmat.$(OBJEXT): clustalw/readmat.cpp
sequence.$(OBJEXT): clustalw/sequence.cpp
showpair.$(OBJEXT): clustalw/showpair.cpp
trees.$(OBJEXT): clustalw/trees.cpp
util.$(OBJEXT): clustalw/util.cpp
element.$(OBJEXT): ipc/element.cpp
gp_out.$(OBJEXT): ipc/gp_out.cpp
ipc.$(OBJEXT): ipc/ipc.cpp
pars.$(OBJEXT): ipc/pars.cpp
GENtle$(EXEEXT): $(GENtle_OBJECTS) $(GENtle_DEPENDENCIES) 
	@rm -f GENtle$(EXEEXT)
	$(CXXLINK) $(GENtle_LDFLAGS) $(GENtle_OBJECTS) $(GENtle_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/ABItype.Po
include ./$(DEPDIR)/ABIviewer.Po
include ./$(DEPDIR)/Alignment.Po
include ./$(DEPDIR)/AminoAcids.Po
include ./$(DEPDIR)/AutoAnnotate.Po
include ./$(DEPDIR)/CGview.Po
include ./$(DEPDIR)/ChildBase.Po
include ./$(DEPDIR)/CoolCanvas.Po
include ./$(DEPDIR)/ExternalBLAST.Po
include ./$(DEPDIR)/ExternalInterface.Po
include ./$(DEPDIR)/ExternalNCBI.Po
include ./$(DEPDIR)/FindSequenceDialog.Po
include ./$(DEPDIR)/GenBank.Po
include ./$(DEPDIR)/ManageDatabase.Po
include ./$(DEPDIR)/MiscDialogs.Po
include ./$(DEPDIR)/MyChild.Po
include ./$(DEPDIR)/MyFrame.Po
include ./$(DEPDIR)/PlasmidCanvas.Po
include ./$(DEPDIR)/PlasmidCanvasCircular.Po
include ./$(DEPDIR)/PlasmidCanvasHandlers.Po
include ./$(DEPDIR)/PlasmidCanvasLinear.Po
include ./$(DEPDIR)/PrimerDesign.Po
include ./$(DEPDIR)/ProgramOptionsDialog.Po
include ./$(DEPDIR)/RestrictionEnzymes.Po
include ./$(DEPDIR)/SendHTTP.Po
include ./$(DEPDIR)/SequenceCanvas.Po
include ./$(DEPDIR)/SequenceTypeAA.Po
include ./$(DEPDIR)/SequenceTypeABI.Po
include ./$(DEPDIR)/SequenceTypeAlign.Po
include ./$(DEPDIR)/SequenceTypeDNA.Po
include ./$(DEPDIR)/SequenceTypeFeature.Po
include ./$(DEPDIR)/SequenceTypePlot.Po
include ./$(DEPDIR)/SequenceTypeRestriction.Po
include ./$(DEPDIR)/SequenceTypes.Po
include ./$(DEPDIR)/TAlignmentDialog.Po
include ./$(DEPDIR)/TCalculator.Po
include ./$(DEPDIR)/TClone.Po
include ./$(DEPDIR)/TGraph.Po
include ./$(DEPDIR)/TGraphDisplay.Po
include ./$(DEPDIR)/TGraphScale.Po
include ./$(DEPDIR)/TIMGreader.Po
include ./$(DEPDIR)/TImageDisplay.Po
include ./$(DEPDIR)/TItemEditDialog.Po
include ./$(DEPDIR)/TLigationDialog.Po
include ./$(DEPDIR)/TMainTree.Po
include ./$(DEPDIR)/TPDB.Po
include ./$(DEPDIR)/TPhylip.Po
include ./$(DEPDIR)/TPhyloTree.Po
include ./$(DEPDIR)/TPrimer.Po
include ./$(DEPDIR)/TPrimerDialog.Po
include ./$(DEPDIR)/TRestrictionEditor.Po
include ./$(DEPDIR)/TSilmutDialog.Po
include ./$(DEPDIR)/TStorage.Po
include ./$(DEPDIR)/TUReadSeq.Po
include ./$(DEPDIR)/TUndo.Po
include ./$(DEPDIR)/TVector.Po
include ./$(DEPDIR)/TVectorEditor.Po
include ./$(DEPDIR)/TVectorEditorEnzymes.Po
include ./$(DEPDIR)/TVectorEditorItems.Po
include ./$(DEPDIR)/TVectorTree.Po
include ./$(DEPDIR)/TVirtualGel.Po
include ./$(DEPDIR)/TXMLfile.Po
include ./$(DEPDIR)/TextImportDialog.Po
include ./$(DEPDIR)/alnscore.Po
include ./$(DEPDIR)/amenu.Po
include ./$(DEPDIR)/calcgap.Po
include ./$(DEPDIR)/calcprf1.Po
include ./$(DEPDIR)/calcprf2.Po
include ./$(DEPDIR)/calctree.Po
include ./$(DEPDIR)/clustalw.Po
include ./$(DEPDIR)/element.Po
include ./$(DEPDIR)/gcgcheck.Po
include ./$(DEPDIR)/gp_out.Po
include ./$(DEPDIR)/interfac.Po
include ./$(DEPDIR)/ipc.Po
include ./$(DEPDIR)/main.Po
include ./$(DEPDIR)/malign.Po
include ./$(DEPDIR)/ncoils.Po
include ./$(DEPDIR)/palign.Po
include ./$(DEPDIR)/pars.Po
include ./$(DEPDIR)/prfalign.Po
include ./$(DEPDIR)/random.Po
include ./$(DEPDIR)/readmat.Po
include ./$(DEPDIR)/sequence.Po
include ./$(DEPDIR)/showpair.Po
include ./$(DEPDIR)/tinystr.Po
include ./$(DEPDIR)/tinyxml.Po
include ./$(DEPDIR)/tinyxmlerror.Po
include ./$(DEPDIR)/tinyxmlparser.Po
include ./$(DEPDIR)/todo.Po
include ./$(DEPDIR)/trees.Po
include ./$(DEPDIR)/ureadseq.Po
include ./$(DEPDIR)/util.Po

distclean-depend:
	-rm -rf ./$(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f '$<' || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`
CCDEPMODE = depmode=gcc3

.cpp.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `test -f '$<' || echo '$(srcdir)/'`$<

.cpp.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`

tinyxmlparser.o: tinyxml/tinyxmlparser.cpp
	source='tinyxml/tinyxmlparser.cpp' object='tinyxmlparser.o' libtool=no \
	depfile='$(DEPDIR)/tinyxmlparser.Po' tmpdepfile='$(DEPDIR)/tinyxmlparser.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxmlparser.o `test -f 'tinyxml/tinyxmlparser.cpp' || echo '$(srcdir)/'`tinyxml/tinyxmlparser.cpp

tinyxmlparser.obj: tinyxml/tinyxmlparser.cpp
	source='tinyxml/tinyxmlparser.cpp' object='tinyxmlparser.obj' libtool=no \
	depfile='$(DEPDIR)/tinyxmlparser.Po' tmpdepfile='$(DEPDIR)/tinyxmlparser.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxmlparser.obj `cygpath -w tinyxml/tinyxmlparser.cpp`

tinyxmlerror.o: tinyxml/tinyxmlerror.cpp
	source='tinyxml/tinyxmlerror.cpp' object='tinyxmlerror.o' libtool=no \
	depfile='$(DEPDIR)/tinyxmlerror.Po' tmpdepfile='$(DEPDIR)/tinyxmlerror.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxmlerror.o `test -f 'tinyxml/tinyxmlerror.cpp' || echo '$(srcdir)/'`tinyxml/tinyxmlerror.cpp

tinyxmlerror.obj: tinyxml/tinyxmlerror.cpp
	source='tinyxml/tinyxmlerror.cpp' object='tinyxmlerror.obj' libtool=no \
	depfile='$(DEPDIR)/tinyxmlerror.Po' tmpdepfile='$(DEPDIR)/tinyxmlerror.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxmlerror.obj `cygpath -w tinyxml/tinyxmlerror.cpp`

tinyxml.o: tinyxml/tinyxml.cpp
	source='tinyxml/tinyxml.cpp' object='tinyxml.o' libtool=no \
	depfile='$(DEPDIR)/tinyxml.Po' tmpdepfile='$(DEPDIR)/tinyxml.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxml.o `test -f 'tinyxml/tinyxml.cpp' || echo '$(srcdir)/'`tinyxml/tinyxml.cpp

tinyxml.obj: tinyxml/tinyxml.cpp
	source='tinyxml/tinyxml.cpp' object='tinyxml.obj' libtool=no \
	depfile='$(DEPDIR)/tinyxml.Po' tmpdepfile='$(DEPDIR)/tinyxml.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxml.obj `cygpath -w tinyxml/tinyxml.cpp`

tinystr.o: tinyxml/tinystr.cpp
	source='tinyxml/tinystr.cpp' object='tinystr.o' libtool=no \
	depfile='$(DEPDIR)/tinystr.Po' tmpdepfile='$(DEPDIR)/tinystr.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinystr.o `test -f 'tinyxml/tinystr.cpp' || echo '$(srcdir)/'`tinyxml/tinystr.cpp

tinystr.obj: tinyxml/tinystr.cpp
	source='tinyxml/tinystr.cpp' object='tinystr.obj' libtool=no \
	depfile='$(DEPDIR)/tinystr.Po' tmpdepfile='$(DEPDIR)/tinystr.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinystr.obj `cygpath -w tinyxml/tinystr.cpp`

alnscore.o: clustalw/alnscore.cpp
	source='clustalw/alnscore.cpp' object='alnscore.o' libtool=no \
	depfile='$(DEPDIR)/alnscore.Po' tmpdepfile='$(DEPDIR)/alnscore.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o alnscore.o `test -f 'clustalw/alnscore.cpp' || echo '$(srcdir)/'`clustalw/alnscore.cpp

alnscore.obj: clustalw/alnscore.cpp
	source='clustalw/alnscore.cpp' object='alnscore.obj' libtool=no \
	depfile='$(DEPDIR)/alnscore.Po' tmpdepfile='$(DEPDIR)/alnscore.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o alnscore.obj `cygpath -w clustalw/alnscore.cpp`

amenu.o: clustalw/amenu.cpp
	source='clustalw/amenu.cpp' object='amenu.o' libtool=no \
	depfile='$(DEPDIR)/amenu.Po' tmpdepfile='$(DEPDIR)/amenu.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o amenu.o `test -f 'clustalw/amenu.cpp' || echo '$(srcdir)/'`clustalw/amenu.cpp

amenu.obj: clustalw/amenu.cpp
	source='clustalw/amenu.cpp' object='amenu.obj' libtool=no \
	depfile='$(DEPDIR)/amenu.Po' tmpdepfile='$(DEPDIR)/amenu.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o amenu.obj `cygpath -w clustalw/amenu.cpp`

calcgap.o: clustalw/calcgap.cpp
	source='clustalw/calcgap.cpp' object='calcgap.o' libtool=no \
	depfile='$(DEPDIR)/calcgap.Po' tmpdepfile='$(DEPDIR)/calcgap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcgap.o `test -f 'clustalw/calcgap.cpp' || echo '$(srcdir)/'`clustalw/calcgap.cpp

calcgap.obj: clustalw/calcgap.cpp
	source='clustalw/calcgap.cpp' object='calcgap.obj' libtool=no \
	depfile='$(DEPDIR)/calcgap.Po' tmpdepfile='$(DEPDIR)/calcgap.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcgap.obj `cygpath -w clustalw/calcgap.cpp`

calcprf1.o: clustalw/calcprf1.cpp
	source='clustalw/calcprf1.cpp' object='calcprf1.o' libtool=no \
	depfile='$(DEPDIR)/calcprf1.Po' tmpdepfile='$(DEPDIR)/calcprf1.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcprf1.o `test -f 'clustalw/calcprf1.cpp' || echo '$(srcdir)/'`clustalw/calcprf1.cpp

calcprf1.obj: clustalw/calcprf1.cpp
	source='clustalw/calcprf1.cpp' object='calcprf1.obj' libtool=no \
	depfile='$(DEPDIR)/calcprf1.Po' tmpdepfile='$(DEPDIR)/calcprf1.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcprf1.obj `cygpath -w clustalw/calcprf1.cpp`

calcprf2.o: clustalw/calcprf2.cpp
	source='clustalw/calcprf2.cpp' object='calcprf2.o' libtool=no \
	depfile='$(DEPDIR)/calcprf2.Po' tmpdepfile='$(DEPDIR)/calcprf2.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcprf2.o `test -f 'clustalw/calcprf2.cpp' || echo '$(srcdir)/'`clustalw/calcprf2.cpp

calcprf2.obj: clustalw/calcprf2.cpp
	source='clustalw/calcprf2.cpp' object='calcprf2.obj' libtool=no \
	depfile='$(DEPDIR)/calcprf2.Po' tmpdepfile='$(DEPDIR)/calcprf2.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcprf2.obj `cygpath -w clustalw/calcprf2.cpp`

calctree.o: clustalw/calctree.cpp
	source='clustalw/calctree.cpp' object='calctree.o' libtool=no \
	depfile='$(DEPDIR)/calctree.Po' tmpdepfile='$(DEPDIR)/calctree.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calctree.o `test -f 'clustalw/calctree.cpp' || echo '$(srcdir)/'`clustalw/calctree.cpp

calctree.obj: clustalw/calctree.cpp
	source='clustalw/calctree.cpp' object='calctree.obj' libtool=no \
	depfile='$(DEPDIR)/calctree.Po' tmpdepfile='$(DEPDIR)/calctree.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calctree.obj `cygpath -w clustalw/calctree.cpp`

clustalw.o: clustalw/clustalw.cpp
	source='clustalw/clustalw.cpp' object='clustalw.o' libtool=no \
	depfile='$(DEPDIR)/clustalw.Po' tmpdepfile='$(DEPDIR)/clustalw.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o clustalw.o `test -f 'clustalw/clustalw.cpp' || echo '$(srcdir)/'`clustalw/clustalw.cpp

clustalw.obj: clustalw/clustalw.cpp
	source='clustalw/clustalw.cpp' object='clustalw.obj' libtool=no \
	depfile='$(DEPDIR)/clustalw.Po' tmpdepfile='$(DEPDIR)/clustalw.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o clustalw.obj `cygpath -w clustalw/clustalw.cpp`

gcgcheck.o: clustalw/gcgcheck.cpp
	source='clustalw/gcgcheck.cpp' object='gcgcheck.o' libtool=no \
	depfile='$(DEPDIR)/gcgcheck.Po' tmpdepfile='$(DEPDIR)/gcgcheck.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gcgcheck.o `test -f 'clustalw/gcgcheck.cpp' || echo '$(srcdir)/'`clustalw/gcgcheck.cpp

gcgcheck.obj: clustalw/gcgcheck.cpp
	source='clustalw/gcgcheck.cpp' object='gcgcheck.obj' libtool=no \
	depfile='$(DEPDIR)/gcgcheck.Po' tmpdepfile='$(DEPDIR)/gcgcheck.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gcgcheck.obj `cygpath -w clustalw/gcgcheck.cpp`

interfac.o: clustalw/interfac.cpp
	source='clustalw/interfac.cpp' object='interfac.o' libtool=no \
	depfile='$(DEPDIR)/interfac.Po' tmpdepfile='$(DEPDIR)/interfac.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o interfac.o `test -f 'clustalw/interfac.cpp' || echo '$(srcdir)/'`clustalw/interfac.cpp

interfac.obj: clustalw/interfac.cpp
	source='clustalw/interfac.cpp' object='interfac.obj' libtool=no \
	depfile='$(DEPDIR)/interfac.Po' tmpdepfile='$(DEPDIR)/interfac.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o interfac.obj `cygpath -w clustalw/interfac.cpp`

malign.o: clustalw/malign.cpp
	source='clustalw/malign.cpp' object='malign.o' libtool=no \
	depfile='$(DEPDIR)/malign.Po' tmpdepfile='$(DEPDIR)/malign.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o malign.o `test -f 'clustalw/malign.cpp' || echo '$(srcdir)/'`clustalw/malign.cpp

malign.obj: clustalw/malign.cpp
	source='clustalw/malign.cpp' object='malign.obj' libtool=no \
	depfile='$(DEPDIR)/malign.Po' tmpdepfile='$(DEPDIR)/malign.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o malign.obj `cygpath -w clustalw/malign.cpp`

palign.o: clustalw/palign.cpp
	source='clustalw/palign.cpp' object='palign.o' libtool=no \
	depfile='$(DEPDIR)/palign.Po' tmpdepfile='$(DEPDIR)/palign.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o palign.o `test -f 'clustalw/palign.cpp' || echo '$(srcdir)/'`clustalw/palign.cpp

palign.obj: clustalw/palign.cpp
	source='clustalw/palign.cpp' object='palign.obj' libtool=no \
	depfile='$(DEPDIR)/palign.Po' tmpdepfile='$(DEPDIR)/palign.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o palign.obj `cygpath -w clustalw/palign.cpp`

prfalign.o: clustalw/prfalign.cpp
	source='clustalw/prfalign.cpp' object='prfalign.o' libtool=no \
	depfile='$(DEPDIR)/prfalign.Po' tmpdepfile='$(DEPDIR)/prfalign.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o prfalign.o `test -f 'clustalw/prfalign.cpp' || echo '$(srcdir)/'`clustalw/prfalign.cpp

prfalign.obj: clustalw/prfalign.cpp
	source='clustalw/prfalign.cpp' object='prfalign.obj' libtool=no \
	depfile='$(DEPDIR)/prfalign.Po' tmpdepfile='$(DEPDIR)/prfalign.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o prfalign.obj `cygpath -w clustalw/prfalign.cpp`

random.o: clustalw/random.cpp
	source='clustalw/random.cpp' object='random.o' libtool=no \
	depfile='$(DEPDIR)/random.Po' tmpdepfile='$(DEPDIR)/random.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o random.o `test -f 'clustalw/random.cpp' || echo '$(srcdir)/'`clustalw/random.cpp

random.obj: clustalw/random.cpp
	source='clustalw/random.cpp' object='random.obj' libtool=no \
	depfile='$(DEPDIR)/random.Po' tmpdepfile='$(DEPDIR)/random.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o random.obj `cygpath -w clustalw/random.cpp`

readmat.o: clustalw/readmat.cpp
	source='clustalw/readmat.cpp' object='readmat.o' libtool=no \
	depfile='$(DEPDIR)/readmat.Po' tmpdepfile='$(DEPDIR)/readmat.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o readmat.o `test -f 'clustalw/readmat.cpp' || echo '$(srcdir)/'`clustalw/readmat.cpp

readmat.obj: clustalw/readmat.cpp
	source='clustalw/readmat.cpp' object='readmat.obj' libtool=no \
	depfile='$(DEPDIR)/readmat.Po' tmpdepfile='$(DEPDIR)/readmat.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o readmat.obj `cygpath -w clustalw/readmat.cpp`

sequence.o: clustalw/sequence.cpp
	source='clustalw/sequence.cpp' object='sequence.o' libtool=no \
	depfile='$(DEPDIR)/sequence.Po' tmpdepfile='$(DEPDIR)/sequence.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sequence.o `test -f 'clustalw/sequence.cpp' || echo '$(srcdir)/'`clustalw/sequence.cpp

sequence.obj: clustalw/sequence.cpp
	source='clustalw/sequence.cpp' object='sequence.obj' libtool=no \
	depfile='$(DEPDIR)/sequence.Po' tmpdepfile='$(DEPDIR)/sequence.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sequence.obj `cygpath -w clustalw/sequence.cpp`

showpair.o: clustalw/showpair.cpp
	source='clustalw/showpair.cpp' object='showpair.o' libtool=no \
	depfile='$(DEPDIR)/showpair.Po' tmpdepfile='$(DEPDIR)/showpair.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o showpair.o `test -f 'clustalw/showpair.cpp' || echo '$(srcdir)/'`clustalw/showpair.cpp

showpair.obj: clustalw/showpair.cpp
	source='clustalw/showpair.cpp' object='showpair.obj' libtool=no \
	depfile='$(DEPDIR)/showpair.Po' tmpdepfile='$(DEPDIR)/showpair.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o showpair.obj `cygpath -w clustalw/showpair.cpp`

trees.o: clustalw/trees.cpp
	source='clustalw/trees.cpp' object='trees.o' libtool=no \
	depfile='$(DEPDIR)/trees.Po' tmpdepfile='$(DEPDIR)/trees.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o trees.o `test -f 'clustalw/trees.cpp' || echo '$(srcdir)/'`clustalw/trees.cpp

trees.obj: clustalw/trees.cpp
	source='clustalw/trees.cpp' object='trees.obj' libtool=no \
	depfile='$(DEPDIR)/trees.Po' tmpdepfile='$(DEPDIR)/trees.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o trees.obj `cygpath -w clustalw/trees.cpp`

util.o: clustalw/util.cpp
	source='clustalw/util.cpp' object='util.o' libtool=no \
	depfile='$(DEPDIR)/util.Po' tmpdepfile='$(DEPDIR)/util.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o util.o `test -f 'clustalw/util.cpp' || echo '$(srcdir)/'`clustalw/util.cpp

util.obj: clustalw/util.cpp
	source='clustalw/util.cpp' object='util.obj' libtool=no \
	depfile='$(DEPDIR)/util.Po' tmpdepfile='$(DEPDIR)/util.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o util.obj `cygpath -w clustalw/util.cpp`

element.o: ipc/element.cpp
	source='ipc/element.cpp' object='element.o' libtool=no \
	depfile='$(DEPDIR)/element.Po' tmpdepfile='$(DEPDIR)/element.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o element.o `test -f 'ipc/element.cpp' || echo '$(srcdir)/'`ipc/element.cpp

element.obj: ipc/element.cpp
	source='ipc/element.cpp' object='element.obj' libtool=no \
	depfile='$(DEPDIR)/element.Po' tmpdepfile='$(DEPDIR)/element.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o element.obj `cygpath -w ipc/element.cpp`

gp_out.o: ipc/gp_out.cpp
	source='ipc/gp_out.cpp' object='gp_out.o' libtool=no \
	depfile='$(DEPDIR)/gp_out.Po' tmpdepfile='$(DEPDIR)/gp_out.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gp_out.o `test -f 'ipc/gp_out.cpp' || echo '$(srcdir)/'`ipc/gp_out.cpp

gp_out.obj: ipc/gp_out.cpp
	source='ipc/gp_out.cpp' object='gp_out.obj' libtool=no \
	depfile='$(DEPDIR)/gp_out.Po' tmpdepfile='$(DEPDIR)/gp_out.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gp_out.obj `cygpath -w ipc/gp_out.cpp`

ipc.o: ipc/ipc.cpp
	source='ipc/ipc.cpp' object='ipc.o' libtool=no \
	depfile='$(DEPDIR)/ipc.Po' tmpdepfile='$(DEPDIR)/ipc.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ipc.o `test -f 'ipc/ipc.cpp' || echo '$(srcdir)/'`ipc/ipc.cpp

ipc.obj: ipc/ipc.cpp
	source='ipc/ipc.cpp' object='ipc.obj' libtool=no \
	depfile='$(DEPDIR)/ipc.Po' tmpdepfile='$(DEPDIR)/ipc.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ipc.obj `cygpath -w ipc/ipc.cpp`

pars.o: ipc/pars.cpp
	source='ipc/pars.cpp' object='pars.o' libtool=no \
	depfile='$(DEPDIR)/pars.Po' tmpdepfile='$(DEPDIR)/pars.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o pars.o `test -f 'ipc/pars.cpp' || echo '$(srcdir)/'`ipc/pars.cpp

pars.obj: ipc/pars.cpp
	source='ipc/pars.cpp' object='pars.obj' libtool=no \
	depfile='$(DEPDIR)/pars.Po' tmpdepfile='$(DEPDIR)/pars.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o pars.obj `cygpath -w ipc/pars.cpp`
CXXDEPMODE = depmode=gcc3
uninstall-info-am:

ETAGS = etags
ETAGSFLAGS =

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$tags$$unique" \
	  || $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = .
distdir = $(PACKAGE)-$(VERSION)

am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }

GZIP_ENV = --best
distcleancheck_listfiles = find . -type f -print

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	$(mkinstalldirs) $(distdir)/bitmaps
	@list='$(DISTFILES)'; for file in $$list; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkinstalldirs) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	$(AMTAR) chof - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist dist-all: distdir
	$(AMTAR) chof - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	$(am__remove_distdir)
	GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(AMTAR) xf -
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/=build
	mkdir $(distdir)/=inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/=inst && pwd` \
	  && cd $(distdir)/=build \
	  && ../configure --srcdir=.. --prefix=$$dc_install_base \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && (test `find $$dc_install_base -type f -print | wc -l` -le 1 \
	      || { echo "ERROR: files left after uninstall:" ; \
	           find $$dc_install_base -type f -print ; \
	           exit 1; } >&2 ) \
	  && $(MAKE) $(AM_MAKEFLAGS) dist-gzip \
	  && rm -f $(distdir).tar.gz \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@echo "$(distdir).tar.gz is ready for distribution" | \
	  sed 'h;s/./=/g;p;x;p;x'
distcleancheck: distclean
	if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(bindir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf autom4te.cache
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic dist dist-all dist-gzip distcheck distclean \
	distclean-compile distclean-depend distclean-generic \
	distclean-tags distcleancheck distdir dvi dvi-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
