# Makefile.in generated by automake 1.9.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SOURCES = $(main_SOURCES)

srcdir = .
top_srcdir = .

pkgdatadir = $(datadir)/GENtle
pkglibdir = $(libdir)/GENtle
pkgincludedir = $(includedir)/GENtle
top_builddir = .
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = main$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL NEWS config.guess config.sub depcomp \
	install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno configure.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am_main_OBJECTS = TXMLfile.$(OBJEXT) TVectorTree.$(OBJEXT) \
	TVirtualGel.$(OBJEXT) TVectorEditorItems.$(OBJEXT) \
	TVectorEditorEnzymes.$(OBJEXT) TVectorEditor.$(OBJEXT) \
	TVector.$(OBJEXT) TUndo.$(OBJEXT) TUReadSeq.$(OBJEXT) \
	TStorage.$(OBJEXT) TSilmutDialog.$(OBJEXT) \
	TRestrictionEditor.$(OBJEXT) TPrimer.$(OBJEXT) \
	TPrimerDialog.$(OBJEXT) TPDB.$(OBJEXT) \
	TLigationDialog.$(OBJEXT) TMainTree.$(OBJEXT) todo.$(OBJEXT) \
	TItemEditDialog.$(OBJEXT) TImageDisplay.$(OBJEXT) \
	TIMGreader.$(OBJEXT) TextImportDialog.$(OBJEXT) \
	TClone.$(OBJEXT) SequenceTypes.$(OBJEXT) TCalculator.$(OBJEXT) \
	SequenceTypeRestriction.$(OBJEXT) SequenceTypePlot.$(OBJEXT) \
	SequenceTypeFeature.$(OBJEXT) SequenceTypeDNA.$(OBJEXT) \
	SequenceTypeAlign.$(OBJEXT) SequenceTypeABI.$(OBJEXT) \
	SequenceTypeAA.$(OBJEXT) SequenceCanvas.$(OBJEXT) \
	SendHTTP.$(OBJEXT) RestrictionEnzymes.$(OBJEXT) \
	ProgramOptionsDialog.$(OBJEXT) PlasmidCanvasLinear.$(OBJEXT) \
	PrimerDesign.$(OBJEXT) PlasmidCanvasHandlers.$(OBJEXT) \
	PlasmidCanvasCircular.$(OBJEXT) PlasmidCanvas.$(OBJEXT) \
	MyFrame.$(OBJEXT) MyChild.$(OBJEXT) MiscDialogs.$(OBJEXT) \
	ManageDatabase.$(OBJEXT) main.$(OBJEXT) GenBank.$(OBJEXT) \
	FindSequenceDialog.$(OBJEXT) ExternalNCBI.$(OBJEXT) \
	ExternalInterface.$(OBJEXT) ExternalBLAST.$(OBJEXT) \
	ChildBase.$(OBJEXT) CoolCanvas.$(OBJEXT) AminoAcids.$(OBJEXT) \
	Alignment.$(OBJEXT) ABIviewer.$(OBJEXT) ABItype.$(OBJEXT) \
	ureadseq.$(OBJEXT) tinyxmlparser.$(OBJEXT) \
	tinyxmlerror.$(OBJEXT) tinyxml.$(OBJEXT) tinystr.$(OBJEXT) \
	alnscore.$(OBJEXT) amenu.$(OBJEXT) calcgap.$(OBJEXT) \
	calcprf1.$(OBJEXT) calcprf2.$(OBJEXT) calctree.$(OBJEXT) \
	clustalw.$(OBJEXT) gcgcheck.$(OBJEXT) interfac.$(OBJEXT) \
	malign.$(OBJEXT) palign.$(OBJEXT) prfalign.$(OBJEXT) \
	random.$(OBJEXT) readmat.$(OBJEXT) sequence.$(OBJEXT) \
	showpair.$(OBJEXT) trees.$(OBJEXT) util.$(OBJEXT)
main_OBJECTS = $(am_main_OBJECTS)
am__DEPENDENCIES_1 =
main_DEPENDENCIES = $(am__DEPENDENCIES_1)
DEFAULT_INCLUDES = -I. -I$(srcdir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
SOURCES = $(main_SOURCES)
DIST_SOURCES = $(main_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/manske/GENtle/missing --run aclocal-1.9
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/manske/GENtle/missing --run tar
AUTOCONF = ${SHELL} /home/manske/GENtle/missing --run autoconf
AUTOHEADER = ${SHELL} /home/manske/GENtle/missing --run autoheader
AUTOMAKE = ${SHELL} /home/manske/GENtle/missing --run automake-1.9
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS =  -I/usr/local/lib/wx/include/gtk2-ansi-release-2.5 -I/usr/local/include/wx-2.5 -DGTK_NO_CHECK_CASTS -D__WXGTK__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2 -I/usr/local/lib/wx/include/gtk2-ansi-release-2.5 -I/usr/local/include/wx-2.5 -DGTK_NO_CHECK_CASTS -D__WXGTK__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"GENtle\" -DVERSION=\"1.5\" 
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/manske/GENtle/missing --run makeinfo
OBJEXT = o
PACKAGE = GENtle
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_VERSION = 
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.5
WX_LIBS = -L/usr/local/lib -pthread   -L/usr/X11R6/lib  -lwx_gtk2_xrc-2.5 -lwx_gtk2_html-2.5 -lwx_gtk2_adv-2.5 -lwx_gtk2_core-2.5 -lwx_base_xml-2.5 -lwx_base_net-2.5 -lwx_base-2.5 
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_STRIP = 
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__fastdepCXX_FALSE = #
am__fastdepCXX_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
datadir = ${prefix}/share
exec_prefix = ${prefix}
host_alias = 
includedir = ${prefix}/include
infodir = ${prefix}/info
install_sh = /home/manske/GENtle/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 
SUFFIXES = .cpp .rc
main_LDADD = $(WX_LIBS) -L/usr/lib -lsqlite -lmysqlclient
main_SOURCES = TXMLfile.cpp\
TVectorTree.cpp\
TVirtualGel.cpp\
TVectorEditorItems.cpp\
TVectorEditorEnzymes.cpp\
TVectorEditor.cpp\
TVector.cpp\
TUndo.cpp\
TUReadSeq.cpp\
TStorage.cpp\
TSilmutDialog.cpp\
TRestrictionEditor.cpp\
TPrimer.cpp\
TPrimerDialog.cpp\
TPDB.cpp\
TLigationDialog.cpp\
TMainTree.cpp\
todo.cpp\
TItemEditDialog.cpp\
TImageDisplay.cpp\
TIMGreader.cpp\
TextImportDialog.cpp\
TClone.cpp\
SequenceTypes.cpp\
TCalculator.cpp\
SequenceTypeRestriction.cpp\
SequenceTypePlot.cpp\
SequenceTypeFeature.cpp\
SequenceTypeDNA.cpp\
SequenceTypeAlign.cpp\
SequenceTypeABI.cpp\
SequenceTypeAA.cpp\
SequenceCanvas.cpp\
SendHTTP.cpp\
RestrictionEnzymes.cpp\
ProgramOptionsDialog.cpp\
PlasmidCanvasLinear.cpp\
PrimerDesign.cpp\
PlasmidCanvasHandlers.cpp\
PlasmidCanvasCircular.cpp\
PlasmidCanvas.cpp\
MyFrame.cpp\
MyChild.cpp\
MiscDialogs.cpp\
ManageDatabase.cpp\
main.cpp\
GenBank.cpp\
FindSequenceDialog.cpp\
ExternalNCBI.cpp\
ExternalInterface.cpp\
ExternalBLAST.cpp\
ChildBase.cpp\
CoolCanvas.cpp\
AminoAcids.cpp\
Alignment.cpp\
ABIviewer.cpp\
ABItype.cpp\
ureadseq.c\
tinyxml/tinyxmlparser.cpp\
tinyxml/tinyxmlerror.cpp\
tinyxml/tinyxml.cpp\
tinyxml/tinystr.cpp\
clustalw/alnscore.cpp\
clustalw/amenu.cpp\
clustalw/calcgap.cpp\
clustalw/calcprf1.cpp\
clustalw/calcprf2.cpp\
clustalw/calctree.cpp\
clustalw/clustalw.cpp\
clustalw/gcgcheck.cpp\
clustalw/interfac.cpp\
clustalw/malign.cpp\
clustalw/palign.cpp\
clustalw/prfalign.cpp\
clustalw/random.cpp\
clustalw/readmat.cpp\
clustalw/sequence.cpp\
clustalw/showpair.cpp\
clustalw/trees.cpp\
clustalw/util.cpp

all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .rc .c .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(mkdir_p) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
main$(EXEEXT): $(main_OBJECTS) $(main_DEPENDENCIES) 
	@rm -f main$(EXEEXT)
	$(CXXLINK) $(main_LDFLAGS) $(main_OBJECTS) $(main_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/ABItype.Po
include ./$(DEPDIR)/ABIviewer.Po
include ./$(DEPDIR)/Alignment.Po
include ./$(DEPDIR)/AminoAcids.Po
include ./$(DEPDIR)/ChildBase.Po
include ./$(DEPDIR)/CoolCanvas.Po
include ./$(DEPDIR)/ExternalBLAST.Po
include ./$(DEPDIR)/ExternalInterface.Po
include ./$(DEPDIR)/ExternalNCBI.Po
include ./$(DEPDIR)/FindSequenceDialog.Po
include ./$(DEPDIR)/GenBank.Po
include ./$(DEPDIR)/ManageDatabase.Po
include ./$(DEPDIR)/MiscDialogs.Po
include ./$(DEPDIR)/MyChild.Po
include ./$(DEPDIR)/MyFrame.Po
include ./$(DEPDIR)/PlasmidCanvas.Po
include ./$(DEPDIR)/PlasmidCanvasCircular.Po
include ./$(DEPDIR)/PlasmidCanvasHandlers.Po
include ./$(DEPDIR)/PlasmidCanvasLinear.Po
include ./$(DEPDIR)/PrimerDesign.Po
include ./$(DEPDIR)/ProgramOptionsDialog.Po
include ./$(DEPDIR)/RestrictionEnzymes.Po
include ./$(DEPDIR)/SendHTTP.Po
include ./$(DEPDIR)/SequenceCanvas.Po
include ./$(DEPDIR)/SequenceTypeAA.Po
include ./$(DEPDIR)/SequenceTypeABI.Po
include ./$(DEPDIR)/SequenceTypeAlign.Po
include ./$(DEPDIR)/SequenceTypeDNA.Po
include ./$(DEPDIR)/SequenceTypeFeature.Po
include ./$(DEPDIR)/SequenceTypePlot.Po
include ./$(DEPDIR)/SequenceTypeRestriction.Po
include ./$(DEPDIR)/SequenceTypes.Po
include ./$(DEPDIR)/TCalculator.Po
include ./$(DEPDIR)/TClone.Po
include ./$(DEPDIR)/TIMGreader.Po
include ./$(DEPDIR)/TImageDisplay.Po
include ./$(DEPDIR)/TItemEditDialog.Po
include ./$(DEPDIR)/TLigationDialog.Po
include ./$(DEPDIR)/TMainTree.Po
include ./$(DEPDIR)/TPDB.Po
include ./$(DEPDIR)/TPrimer.Po
include ./$(DEPDIR)/TPrimerDialog.Po
include ./$(DEPDIR)/TRestrictionEditor.Po
include ./$(DEPDIR)/TSilmutDialog.Po
include ./$(DEPDIR)/TStorage.Po
include ./$(DEPDIR)/TUReadSeq.Po
include ./$(DEPDIR)/TUndo.Po
include ./$(DEPDIR)/TVector.Po
include ./$(DEPDIR)/TVectorEditor.Po
include ./$(DEPDIR)/TVectorEditorEnzymes.Po
include ./$(DEPDIR)/TVectorEditorItems.Po
include ./$(DEPDIR)/TVectorTree.Po
include ./$(DEPDIR)/TVirtualGel.Po
include ./$(DEPDIR)/TXMLfile.Po
include ./$(DEPDIR)/TextImportDialog.Po
include ./$(DEPDIR)/alnscore.Po
include ./$(DEPDIR)/amenu.Po
include ./$(DEPDIR)/calcgap.Po
include ./$(DEPDIR)/calcprf1.Po
include ./$(DEPDIR)/calcprf2.Po
include ./$(DEPDIR)/calctree.Po
include ./$(DEPDIR)/clustalw.Po
include ./$(DEPDIR)/gcgcheck.Po
include ./$(DEPDIR)/interfac.Po
include ./$(DEPDIR)/main.Po
include ./$(DEPDIR)/malign.Po
include ./$(DEPDIR)/palign.Po
include ./$(DEPDIR)/prfalign.Po
include ./$(DEPDIR)/random.Po
include ./$(DEPDIR)/readmat.Po
include ./$(DEPDIR)/sequence.Po
include ./$(DEPDIR)/showpair.Po
include ./$(DEPDIR)/tinystr.Po
include ./$(DEPDIR)/tinyxml.Po
include ./$(DEPDIR)/tinyxmlerror.Po
include ./$(DEPDIR)/tinyxmlparser.Po
include ./$(DEPDIR)/todo.Po
include ./$(DEPDIR)/trees.Po
include ./$(DEPDIR)/ureadseq.Po
include ./$(DEPDIR)/util.Po

.c.o:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.cpp.o:
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

tinyxmlparser.o: tinyxml/tinyxmlparser.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tinyxmlparser.o -MD -MP -MF "$(DEPDIR)/tinyxmlparser.Tpo" -c -o tinyxmlparser.o `test -f 'tinyxml/tinyxmlparser.cpp' || echo '$(srcdir)/'`tinyxml/tinyxmlparser.cpp; \
	then mv -f "$(DEPDIR)/tinyxmlparser.Tpo" "$(DEPDIR)/tinyxmlparser.Po"; else rm -f "$(DEPDIR)/tinyxmlparser.Tpo"; exit 1; fi
#	source='tinyxml/tinyxmlparser.cpp' object='tinyxmlparser.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxmlparser.o `test -f 'tinyxml/tinyxmlparser.cpp' || echo '$(srcdir)/'`tinyxml/tinyxmlparser.cpp

tinyxmlparser.obj: tinyxml/tinyxmlparser.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tinyxmlparser.obj -MD -MP -MF "$(DEPDIR)/tinyxmlparser.Tpo" -c -o tinyxmlparser.obj `if test -f 'tinyxml/tinyxmlparser.cpp'; then $(CYGPATH_W) 'tinyxml/tinyxmlparser.cpp'; else $(CYGPATH_W) '$(srcdir)/tinyxml/tinyxmlparser.cpp'; fi`; \
	then mv -f "$(DEPDIR)/tinyxmlparser.Tpo" "$(DEPDIR)/tinyxmlparser.Po"; else rm -f "$(DEPDIR)/tinyxmlparser.Tpo"; exit 1; fi
#	source='tinyxml/tinyxmlparser.cpp' object='tinyxmlparser.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxmlparser.obj `if test -f 'tinyxml/tinyxmlparser.cpp'; then $(CYGPATH_W) 'tinyxml/tinyxmlparser.cpp'; else $(CYGPATH_W) '$(srcdir)/tinyxml/tinyxmlparser.cpp'; fi`

tinyxmlerror.o: tinyxml/tinyxmlerror.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tinyxmlerror.o -MD -MP -MF "$(DEPDIR)/tinyxmlerror.Tpo" -c -o tinyxmlerror.o `test -f 'tinyxml/tinyxmlerror.cpp' || echo '$(srcdir)/'`tinyxml/tinyxmlerror.cpp; \
	then mv -f "$(DEPDIR)/tinyxmlerror.Tpo" "$(DEPDIR)/tinyxmlerror.Po"; else rm -f "$(DEPDIR)/tinyxmlerror.Tpo"; exit 1; fi
#	source='tinyxml/tinyxmlerror.cpp' object='tinyxmlerror.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxmlerror.o `test -f 'tinyxml/tinyxmlerror.cpp' || echo '$(srcdir)/'`tinyxml/tinyxmlerror.cpp

tinyxmlerror.obj: tinyxml/tinyxmlerror.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tinyxmlerror.obj -MD -MP -MF "$(DEPDIR)/tinyxmlerror.Tpo" -c -o tinyxmlerror.obj `if test -f 'tinyxml/tinyxmlerror.cpp'; then $(CYGPATH_W) 'tinyxml/tinyxmlerror.cpp'; else $(CYGPATH_W) '$(srcdir)/tinyxml/tinyxmlerror.cpp'; fi`; \
	then mv -f "$(DEPDIR)/tinyxmlerror.Tpo" "$(DEPDIR)/tinyxmlerror.Po"; else rm -f "$(DEPDIR)/tinyxmlerror.Tpo"; exit 1; fi
#	source='tinyxml/tinyxmlerror.cpp' object='tinyxmlerror.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxmlerror.obj `if test -f 'tinyxml/tinyxmlerror.cpp'; then $(CYGPATH_W) 'tinyxml/tinyxmlerror.cpp'; else $(CYGPATH_W) '$(srcdir)/tinyxml/tinyxmlerror.cpp'; fi`

tinyxml.o: tinyxml/tinyxml.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tinyxml.o -MD -MP -MF "$(DEPDIR)/tinyxml.Tpo" -c -o tinyxml.o `test -f 'tinyxml/tinyxml.cpp' || echo '$(srcdir)/'`tinyxml/tinyxml.cpp; \
	then mv -f "$(DEPDIR)/tinyxml.Tpo" "$(DEPDIR)/tinyxml.Po"; else rm -f "$(DEPDIR)/tinyxml.Tpo"; exit 1; fi
#	source='tinyxml/tinyxml.cpp' object='tinyxml.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxml.o `test -f 'tinyxml/tinyxml.cpp' || echo '$(srcdir)/'`tinyxml/tinyxml.cpp

tinyxml.obj: tinyxml/tinyxml.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tinyxml.obj -MD -MP -MF "$(DEPDIR)/tinyxml.Tpo" -c -o tinyxml.obj `if test -f 'tinyxml/tinyxml.cpp'; then $(CYGPATH_W) 'tinyxml/tinyxml.cpp'; else $(CYGPATH_W) '$(srcdir)/tinyxml/tinyxml.cpp'; fi`; \
	then mv -f "$(DEPDIR)/tinyxml.Tpo" "$(DEPDIR)/tinyxml.Po"; else rm -f "$(DEPDIR)/tinyxml.Tpo"; exit 1; fi
#	source='tinyxml/tinyxml.cpp' object='tinyxml.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinyxml.obj `if test -f 'tinyxml/tinyxml.cpp'; then $(CYGPATH_W) 'tinyxml/tinyxml.cpp'; else $(CYGPATH_W) '$(srcdir)/tinyxml/tinyxml.cpp'; fi`

tinystr.o: tinyxml/tinystr.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tinystr.o -MD -MP -MF "$(DEPDIR)/tinystr.Tpo" -c -o tinystr.o `test -f 'tinyxml/tinystr.cpp' || echo '$(srcdir)/'`tinyxml/tinystr.cpp; \
	then mv -f "$(DEPDIR)/tinystr.Tpo" "$(DEPDIR)/tinystr.Po"; else rm -f "$(DEPDIR)/tinystr.Tpo"; exit 1; fi
#	source='tinyxml/tinystr.cpp' object='tinystr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinystr.o `test -f 'tinyxml/tinystr.cpp' || echo '$(srcdir)/'`tinyxml/tinystr.cpp

tinystr.obj: tinyxml/tinystr.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tinystr.obj -MD -MP -MF "$(DEPDIR)/tinystr.Tpo" -c -o tinystr.obj `if test -f 'tinyxml/tinystr.cpp'; then $(CYGPATH_W) 'tinyxml/tinystr.cpp'; else $(CYGPATH_W) '$(srcdir)/tinyxml/tinystr.cpp'; fi`; \
	then mv -f "$(DEPDIR)/tinystr.Tpo" "$(DEPDIR)/tinystr.Po"; else rm -f "$(DEPDIR)/tinystr.Tpo"; exit 1; fi
#	source='tinyxml/tinystr.cpp' object='tinystr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tinystr.obj `if test -f 'tinyxml/tinystr.cpp'; then $(CYGPATH_W) 'tinyxml/tinystr.cpp'; else $(CYGPATH_W) '$(srcdir)/tinyxml/tinystr.cpp'; fi`

alnscore.o: clustalw/alnscore.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT alnscore.o -MD -MP -MF "$(DEPDIR)/alnscore.Tpo" -c -o alnscore.o `test -f 'clustalw/alnscore.cpp' || echo '$(srcdir)/'`clustalw/alnscore.cpp; \
	then mv -f "$(DEPDIR)/alnscore.Tpo" "$(DEPDIR)/alnscore.Po"; else rm -f "$(DEPDIR)/alnscore.Tpo"; exit 1; fi
#	source='clustalw/alnscore.cpp' object='alnscore.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o alnscore.o `test -f 'clustalw/alnscore.cpp' || echo '$(srcdir)/'`clustalw/alnscore.cpp

alnscore.obj: clustalw/alnscore.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT alnscore.obj -MD -MP -MF "$(DEPDIR)/alnscore.Tpo" -c -o alnscore.obj `if test -f 'clustalw/alnscore.cpp'; then $(CYGPATH_W) 'clustalw/alnscore.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/alnscore.cpp'; fi`; \
	then mv -f "$(DEPDIR)/alnscore.Tpo" "$(DEPDIR)/alnscore.Po"; else rm -f "$(DEPDIR)/alnscore.Tpo"; exit 1; fi
#	source='clustalw/alnscore.cpp' object='alnscore.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o alnscore.obj `if test -f 'clustalw/alnscore.cpp'; then $(CYGPATH_W) 'clustalw/alnscore.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/alnscore.cpp'; fi`

amenu.o: clustalw/amenu.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT amenu.o -MD -MP -MF "$(DEPDIR)/amenu.Tpo" -c -o amenu.o `test -f 'clustalw/amenu.cpp' || echo '$(srcdir)/'`clustalw/amenu.cpp; \
	then mv -f "$(DEPDIR)/amenu.Tpo" "$(DEPDIR)/amenu.Po"; else rm -f "$(DEPDIR)/amenu.Tpo"; exit 1; fi
#	source='clustalw/amenu.cpp' object='amenu.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o amenu.o `test -f 'clustalw/amenu.cpp' || echo '$(srcdir)/'`clustalw/amenu.cpp

amenu.obj: clustalw/amenu.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT amenu.obj -MD -MP -MF "$(DEPDIR)/amenu.Tpo" -c -o amenu.obj `if test -f 'clustalw/amenu.cpp'; then $(CYGPATH_W) 'clustalw/amenu.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/amenu.cpp'; fi`; \
	then mv -f "$(DEPDIR)/amenu.Tpo" "$(DEPDIR)/amenu.Po"; else rm -f "$(DEPDIR)/amenu.Tpo"; exit 1; fi
#	source='clustalw/amenu.cpp' object='amenu.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o amenu.obj `if test -f 'clustalw/amenu.cpp'; then $(CYGPATH_W) 'clustalw/amenu.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/amenu.cpp'; fi`

calcgap.o: clustalw/calcgap.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT calcgap.o -MD -MP -MF "$(DEPDIR)/calcgap.Tpo" -c -o calcgap.o `test -f 'clustalw/calcgap.cpp' || echo '$(srcdir)/'`clustalw/calcgap.cpp; \
	then mv -f "$(DEPDIR)/calcgap.Tpo" "$(DEPDIR)/calcgap.Po"; else rm -f "$(DEPDIR)/calcgap.Tpo"; exit 1; fi
#	source='clustalw/calcgap.cpp' object='calcgap.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcgap.o `test -f 'clustalw/calcgap.cpp' || echo '$(srcdir)/'`clustalw/calcgap.cpp

calcgap.obj: clustalw/calcgap.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT calcgap.obj -MD -MP -MF "$(DEPDIR)/calcgap.Tpo" -c -o calcgap.obj `if test -f 'clustalw/calcgap.cpp'; then $(CYGPATH_W) 'clustalw/calcgap.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/calcgap.cpp'; fi`; \
	then mv -f "$(DEPDIR)/calcgap.Tpo" "$(DEPDIR)/calcgap.Po"; else rm -f "$(DEPDIR)/calcgap.Tpo"; exit 1; fi
#	source='clustalw/calcgap.cpp' object='calcgap.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcgap.obj `if test -f 'clustalw/calcgap.cpp'; then $(CYGPATH_W) 'clustalw/calcgap.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/calcgap.cpp'; fi`

calcprf1.o: clustalw/calcprf1.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT calcprf1.o -MD -MP -MF "$(DEPDIR)/calcprf1.Tpo" -c -o calcprf1.o `test -f 'clustalw/calcprf1.cpp' || echo '$(srcdir)/'`clustalw/calcprf1.cpp; \
	then mv -f "$(DEPDIR)/calcprf1.Tpo" "$(DEPDIR)/calcprf1.Po"; else rm -f "$(DEPDIR)/calcprf1.Tpo"; exit 1; fi
#	source='clustalw/calcprf1.cpp' object='calcprf1.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcprf1.o `test -f 'clustalw/calcprf1.cpp' || echo '$(srcdir)/'`clustalw/calcprf1.cpp

calcprf1.obj: clustalw/calcprf1.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT calcprf1.obj -MD -MP -MF "$(DEPDIR)/calcprf1.Tpo" -c -o calcprf1.obj `if test -f 'clustalw/calcprf1.cpp'; then $(CYGPATH_W) 'clustalw/calcprf1.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/calcprf1.cpp'; fi`; \
	then mv -f "$(DEPDIR)/calcprf1.Tpo" "$(DEPDIR)/calcprf1.Po"; else rm -f "$(DEPDIR)/calcprf1.Tpo"; exit 1; fi
#	source='clustalw/calcprf1.cpp' object='calcprf1.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcprf1.obj `if test -f 'clustalw/calcprf1.cpp'; then $(CYGPATH_W) 'clustalw/calcprf1.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/calcprf1.cpp'; fi`

calcprf2.o: clustalw/calcprf2.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT calcprf2.o -MD -MP -MF "$(DEPDIR)/calcprf2.Tpo" -c -o calcprf2.o `test -f 'clustalw/calcprf2.cpp' || echo '$(srcdir)/'`clustalw/calcprf2.cpp; \
	then mv -f "$(DEPDIR)/calcprf2.Tpo" "$(DEPDIR)/calcprf2.Po"; else rm -f "$(DEPDIR)/calcprf2.Tpo"; exit 1; fi
#	source='clustalw/calcprf2.cpp' object='calcprf2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcprf2.o `test -f 'clustalw/calcprf2.cpp' || echo '$(srcdir)/'`clustalw/calcprf2.cpp

calcprf2.obj: clustalw/calcprf2.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT calcprf2.obj -MD -MP -MF "$(DEPDIR)/calcprf2.Tpo" -c -o calcprf2.obj `if test -f 'clustalw/calcprf2.cpp'; then $(CYGPATH_W) 'clustalw/calcprf2.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/calcprf2.cpp'; fi`; \
	then mv -f "$(DEPDIR)/calcprf2.Tpo" "$(DEPDIR)/calcprf2.Po"; else rm -f "$(DEPDIR)/calcprf2.Tpo"; exit 1; fi
#	source='clustalw/calcprf2.cpp' object='calcprf2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calcprf2.obj `if test -f 'clustalw/calcprf2.cpp'; then $(CYGPATH_W) 'clustalw/calcprf2.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/calcprf2.cpp'; fi`

calctree.o: clustalw/calctree.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT calctree.o -MD -MP -MF "$(DEPDIR)/calctree.Tpo" -c -o calctree.o `test -f 'clustalw/calctree.cpp' || echo '$(srcdir)/'`clustalw/calctree.cpp; \
	then mv -f "$(DEPDIR)/calctree.Tpo" "$(DEPDIR)/calctree.Po"; else rm -f "$(DEPDIR)/calctree.Tpo"; exit 1; fi
#	source='clustalw/calctree.cpp' object='calctree.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calctree.o `test -f 'clustalw/calctree.cpp' || echo '$(srcdir)/'`clustalw/calctree.cpp

calctree.obj: clustalw/calctree.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT calctree.obj -MD -MP -MF "$(DEPDIR)/calctree.Tpo" -c -o calctree.obj `if test -f 'clustalw/calctree.cpp'; then $(CYGPATH_W) 'clustalw/calctree.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/calctree.cpp'; fi`; \
	then mv -f "$(DEPDIR)/calctree.Tpo" "$(DEPDIR)/calctree.Po"; else rm -f "$(DEPDIR)/calctree.Tpo"; exit 1; fi
#	source='clustalw/calctree.cpp' object='calctree.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o calctree.obj `if test -f 'clustalw/calctree.cpp'; then $(CYGPATH_W) 'clustalw/calctree.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/calctree.cpp'; fi`

clustalw.o: clustalw/clustalw.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT clustalw.o -MD -MP -MF "$(DEPDIR)/clustalw.Tpo" -c -o clustalw.o `test -f 'clustalw/clustalw.cpp' || echo '$(srcdir)/'`clustalw/clustalw.cpp; \
	then mv -f "$(DEPDIR)/clustalw.Tpo" "$(DEPDIR)/clustalw.Po"; else rm -f "$(DEPDIR)/clustalw.Tpo"; exit 1; fi
#	source='clustalw/clustalw.cpp' object='clustalw.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o clustalw.o `test -f 'clustalw/clustalw.cpp' || echo '$(srcdir)/'`clustalw/clustalw.cpp

clustalw.obj: clustalw/clustalw.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT clustalw.obj -MD -MP -MF "$(DEPDIR)/clustalw.Tpo" -c -o clustalw.obj `if test -f 'clustalw/clustalw.cpp'; then $(CYGPATH_W) 'clustalw/clustalw.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/clustalw.cpp'; fi`; \
	then mv -f "$(DEPDIR)/clustalw.Tpo" "$(DEPDIR)/clustalw.Po"; else rm -f "$(DEPDIR)/clustalw.Tpo"; exit 1; fi
#	source='clustalw/clustalw.cpp' object='clustalw.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o clustalw.obj `if test -f 'clustalw/clustalw.cpp'; then $(CYGPATH_W) 'clustalw/clustalw.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/clustalw.cpp'; fi`

gcgcheck.o: clustalw/gcgcheck.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gcgcheck.o -MD -MP -MF "$(DEPDIR)/gcgcheck.Tpo" -c -o gcgcheck.o `test -f 'clustalw/gcgcheck.cpp' || echo '$(srcdir)/'`clustalw/gcgcheck.cpp; \
	then mv -f "$(DEPDIR)/gcgcheck.Tpo" "$(DEPDIR)/gcgcheck.Po"; else rm -f "$(DEPDIR)/gcgcheck.Tpo"; exit 1; fi
#	source='clustalw/gcgcheck.cpp' object='gcgcheck.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gcgcheck.o `test -f 'clustalw/gcgcheck.cpp' || echo '$(srcdir)/'`clustalw/gcgcheck.cpp

gcgcheck.obj: clustalw/gcgcheck.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gcgcheck.obj -MD -MP -MF "$(DEPDIR)/gcgcheck.Tpo" -c -o gcgcheck.obj `if test -f 'clustalw/gcgcheck.cpp'; then $(CYGPATH_W) 'clustalw/gcgcheck.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/gcgcheck.cpp'; fi`; \
	then mv -f "$(DEPDIR)/gcgcheck.Tpo" "$(DEPDIR)/gcgcheck.Po"; else rm -f "$(DEPDIR)/gcgcheck.Tpo"; exit 1; fi
#	source='clustalw/gcgcheck.cpp' object='gcgcheck.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gcgcheck.obj `if test -f 'clustalw/gcgcheck.cpp'; then $(CYGPATH_W) 'clustalw/gcgcheck.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/gcgcheck.cpp'; fi`

interfac.o: clustalw/interfac.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT interfac.o -MD -MP -MF "$(DEPDIR)/interfac.Tpo" -c -o interfac.o `test -f 'clustalw/interfac.cpp' || echo '$(srcdir)/'`clustalw/interfac.cpp; \
	then mv -f "$(DEPDIR)/interfac.Tpo" "$(DEPDIR)/interfac.Po"; else rm -f "$(DEPDIR)/interfac.Tpo"; exit 1; fi
#	source='clustalw/interfac.cpp' object='interfac.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o interfac.o `test -f 'clustalw/interfac.cpp' || echo '$(srcdir)/'`clustalw/interfac.cpp

interfac.obj: clustalw/interfac.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT interfac.obj -MD -MP -MF "$(DEPDIR)/interfac.Tpo" -c -o interfac.obj `if test -f 'clustalw/interfac.cpp'; then $(CYGPATH_W) 'clustalw/interfac.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/interfac.cpp'; fi`; \
	then mv -f "$(DEPDIR)/interfac.Tpo" "$(DEPDIR)/interfac.Po"; else rm -f "$(DEPDIR)/interfac.Tpo"; exit 1; fi
#	source='clustalw/interfac.cpp' object='interfac.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o interfac.obj `if test -f 'clustalw/interfac.cpp'; then $(CYGPATH_W) 'clustalw/interfac.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/interfac.cpp'; fi`

malign.o: clustalw/malign.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT malign.o -MD -MP -MF "$(DEPDIR)/malign.Tpo" -c -o malign.o `test -f 'clustalw/malign.cpp' || echo '$(srcdir)/'`clustalw/malign.cpp; \
	then mv -f "$(DEPDIR)/malign.Tpo" "$(DEPDIR)/malign.Po"; else rm -f "$(DEPDIR)/malign.Tpo"; exit 1; fi
#	source='clustalw/malign.cpp' object='malign.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o malign.o `test -f 'clustalw/malign.cpp' || echo '$(srcdir)/'`clustalw/malign.cpp

malign.obj: clustalw/malign.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT malign.obj -MD -MP -MF "$(DEPDIR)/malign.Tpo" -c -o malign.obj `if test -f 'clustalw/malign.cpp'; then $(CYGPATH_W) 'clustalw/malign.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/malign.cpp'; fi`; \
	then mv -f "$(DEPDIR)/malign.Tpo" "$(DEPDIR)/malign.Po"; else rm -f "$(DEPDIR)/malign.Tpo"; exit 1; fi
#	source='clustalw/malign.cpp' object='malign.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o malign.obj `if test -f 'clustalw/malign.cpp'; then $(CYGPATH_W) 'clustalw/malign.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/malign.cpp'; fi`

palign.o: clustalw/palign.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT palign.o -MD -MP -MF "$(DEPDIR)/palign.Tpo" -c -o palign.o `test -f 'clustalw/palign.cpp' || echo '$(srcdir)/'`clustalw/palign.cpp; \
	then mv -f "$(DEPDIR)/palign.Tpo" "$(DEPDIR)/palign.Po"; else rm -f "$(DEPDIR)/palign.Tpo"; exit 1; fi
#	source='clustalw/palign.cpp' object='palign.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o palign.o `test -f 'clustalw/palign.cpp' || echo '$(srcdir)/'`clustalw/palign.cpp

palign.obj: clustalw/palign.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT palign.obj -MD -MP -MF "$(DEPDIR)/palign.Tpo" -c -o palign.obj `if test -f 'clustalw/palign.cpp'; then $(CYGPATH_W) 'clustalw/palign.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/palign.cpp'; fi`; \
	then mv -f "$(DEPDIR)/palign.Tpo" "$(DEPDIR)/palign.Po"; else rm -f "$(DEPDIR)/palign.Tpo"; exit 1; fi
#	source='clustalw/palign.cpp' object='palign.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o palign.obj `if test -f 'clustalw/palign.cpp'; then $(CYGPATH_W) 'clustalw/palign.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/palign.cpp'; fi`

prfalign.o: clustalw/prfalign.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT prfalign.o -MD -MP -MF "$(DEPDIR)/prfalign.Tpo" -c -o prfalign.o `test -f 'clustalw/prfalign.cpp' || echo '$(srcdir)/'`clustalw/prfalign.cpp; \
	then mv -f "$(DEPDIR)/prfalign.Tpo" "$(DEPDIR)/prfalign.Po"; else rm -f "$(DEPDIR)/prfalign.Tpo"; exit 1; fi
#	source='clustalw/prfalign.cpp' object='prfalign.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o prfalign.o `test -f 'clustalw/prfalign.cpp' || echo '$(srcdir)/'`clustalw/prfalign.cpp

prfalign.obj: clustalw/prfalign.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT prfalign.obj -MD -MP -MF "$(DEPDIR)/prfalign.Tpo" -c -o prfalign.obj `if test -f 'clustalw/prfalign.cpp'; then $(CYGPATH_W) 'clustalw/prfalign.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/prfalign.cpp'; fi`; \
	then mv -f "$(DEPDIR)/prfalign.Tpo" "$(DEPDIR)/prfalign.Po"; else rm -f "$(DEPDIR)/prfalign.Tpo"; exit 1; fi
#	source='clustalw/prfalign.cpp' object='prfalign.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o prfalign.obj `if test -f 'clustalw/prfalign.cpp'; then $(CYGPATH_W) 'clustalw/prfalign.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/prfalign.cpp'; fi`

random.o: clustalw/random.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT random.o -MD -MP -MF "$(DEPDIR)/random.Tpo" -c -o random.o `test -f 'clustalw/random.cpp' || echo '$(srcdir)/'`clustalw/random.cpp; \
	then mv -f "$(DEPDIR)/random.Tpo" "$(DEPDIR)/random.Po"; else rm -f "$(DEPDIR)/random.Tpo"; exit 1; fi
#	source='clustalw/random.cpp' object='random.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o random.o `test -f 'clustalw/random.cpp' || echo '$(srcdir)/'`clustalw/random.cpp

random.obj: clustalw/random.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT random.obj -MD -MP -MF "$(DEPDIR)/random.Tpo" -c -o random.obj `if test -f 'clustalw/random.cpp'; then $(CYGPATH_W) 'clustalw/random.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/random.cpp'; fi`; \
	then mv -f "$(DEPDIR)/random.Tpo" "$(DEPDIR)/random.Po"; else rm -f "$(DEPDIR)/random.Tpo"; exit 1; fi
#	source='clustalw/random.cpp' object='random.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o random.obj `if test -f 'clustalw/random.cpp'; then $(CYGPATH_W) 'clustalw/random.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/random.cpp'; fi`

readmat.o: clustalw/readmat.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT readmat.o -MD -MP -MF "$(DEPDIR)/readmat.Tpo" -c -o readmat.o `test -f 'clustalw/readmat.cpp' || echo '$(srcdir)/'`clustalw/readmat.cpp; \
	then mv -f "$(DEPDIR)/readmat.Tpo" "$(DEPDIR)/readmat.Po"; else rm -f "$(DEPDIR)/readmat.Tpo"; exit 1; fi
#	source='clustalw/readmat.cpp' object='readmat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o readmat.o `test -f 'clustalw/readmat.cpp' || echo '$(srcdir)/'`clustalw/readmat.cpp

readmat.obj: clustalw/readmat.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT readmat.obj -MD -MP -MF "$(DEPDIR)/readmat.Tpo" -c -o readmat.obj `if test -f 'clustalw/readmat.cpp'; then $(CYGPATH_W) 'clustalw/readmat.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/readmat.cpp'; fi`; \
	then mv -f "$(DEPDIR)/readmat.Tpo" "$(DEPDIR)/readmat.Po"; else rm -f "$(DEPDIR)/readmat.Tpo"; exit 1; fi
#	source='clustalw/readmat.cpp' object='readmat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o readmat.obj `if test -f 'clustalw/readmat.cpp'; then $(CYGPATH_W) 'clustalw/readmat.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/readmat.cpp'; fi`

sequence.o: clustalw/sequence.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sequence.o -MD -MP -MF "$(DEPDIR)/sequence.Tpo" -c -o sequence.o `test -f 'clustalw/sequence.cpp' || echo '$(srcdir)/'`clustalw/sequence.cpp; \
	then mv -f "$(DEPDIR)/sequence.Tpo" "$(DEPDIR)/sequence.Po"; else rm -f "$(DEPDIR)/sequence.Tpo"; exit 1; fi
#	source='clustalw/sequence.cpp' object='sequence.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sequence.o `test -f 'clustalw/sequence.cpp' || echo '$(srcdir)/'`clustalw/sequence.cpp

sequence.obj: clustalw/sequence.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sequence.obj -MD -MP -MF "$(DEPDIR)/sequence.Tpo" -c -o sequence.obj `if test -f 'clustalw/sequence.cpp'; then $(CYGPATH_W) 'clustalw/sequence.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/sequence.cpp'; fi`; \
	then mv -f "$(DEPDIR)/sequence.Tpo" "$(DEPDIR)/sequence.Po"; else rm -f "$(DEPDIR)/sequence.Tpo"; exit 1; fi
#	source='clustalw/sequence.cpp' object='sequence.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sequence.obj `if test -f 'clustalw/sequence.cpp'; then $(CYGPATH_W) 'clustalw/sequence.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/sequence.cpp'; fi`

showpair.o: clustalw/showpair.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT showpair.o -MD -MP -MF "$(DEPDIR)/showpair.Tpo" -c -o showpair.o `test -f 'clustalw/showpair.cpp' || echo '$(srcdir)/'`clustalw/showpair.cpp; \
	then mv -f "$(DEPDIR)/showpair.Tpo" "$(DEPDIR)/showpair.Po"; else rm -f "$(DEPDIR)/showpair.Tpo"; exit 1; fi
#	source='clustalw/showpair.cpp' object='showpair.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o showpair.o `test -f 'clustalw/showpair.cpp' || echo '$(srcdir)/'`clustalw/showpair.cpp

showpair.obj: clustalw/showpair.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT showpair.obj -MD -MP -MF "$(DEPDIR)/showpair.Tpo" -c -o showpair.obj `if test -f 'clustalw/showpair.cpp'; then $(CYGPATH_W) 'clustalw/showpair.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/showpair.cpp'; fi`; \
	then mv -f "$(DEPDIR)/showpair.Tpo" "$(DEPDIR)/showpair.Po"; else rm -f "$(DEPDIR)/showpair.Tpo"; exit 1; fi
#	source='clustalw/showpair.cpp' object='showpair.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o showpair.obj `if test -f 'clustalw/showpair.cpp'; then $(CYGPATH_W) 'clustalw/showpair.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/showpair.cpp'; fi`

trees.o: clustalw/trees.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT trees.o -MD -MP -MF "$(DEPDIR)/trees.Tpo" -c -o trees.o `test -f 'clustalw/trees.cpp' || echo '$(srcdir)/'`clustalw/trees.cpp; \
	then mv -f "$(DEPDIR)/trees.Tpo" "$(DEPDIR)/trees.Po"; else rm -f "$(DEPDIR)/trees.Tpo"; exit 1; fi
#	source='clustalw/trees.cpp' object='trees.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o trees.o `test -f 'clustalw/trees.cpp' || echo '$(srcdir)/'`clustalw/trees.cpp

trees.obj: clustalw/trees.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT trees.obj -MD -MP -MF "$(DEPDIR)/trees.Tpo" -c -o trees.obj `if test -f 'clustalw/trees.cpp'; then $(CYGPATH_W) 'clustalw/trees.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/trees.cpp'; fi`; \
	then mv -f "$(DEPDIR)/trees.Tpo" "$(DEPDIR)/trees.Po"; else rm -f "$(DEPDIR)/trees.Tpo"; exit 1; fi
#	source='clustalw/trees.cpp' object='trees.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o trees.obj `if test -f 'clustalw/trees.cpp'; then $(CYGPATH_W) 'clustalw/trees.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/trees.cpp'; fi`

util.o: clustalw/util.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT util.o -MD -MP -MF "$(DEPDIR)/util.Tpo" -c -o util.o `test -f 'clustalw/util.cpp' || echo '$(srcdir)/'`clustalw/util.cpp; \
	then mv -f "$(DEPDIR)/util.Tpo" "$(DEPDIR)/util.Po"; else rm -f "$(DEPDIR)/util.Tpo"; exit 1; fi
#	source='clustalw/util.cpp' object='util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o util.o `test -f 'clustalw/util.cpp' || echo '$(srcdir)/'`clustalw/util.cpp

util.obj: clustalw/util.cpp
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT util.obj -MD -MP -MF "$(DEPDIR)/util.Tpo" -c -o util.obj `if test -f 'clustalw/util.cpp'; then $(CYGPATH_W) 'clustalw/util.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/util.cpp'; fi`; \
	then mv -f "$(DEPDIR)/util.Tpo" "$(DEPDIR)/util.Po"; else rm -f "$(DEPDIR)/util.Tpo"; exit 1; fi
#	source='clustalw/util.cpp' object='util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o util.obj `if test -f 'clustalw/util.cpp'; then $(CYGPATH_W) 'clustalw/util.cpp'; else $(CYGPATH_W) '$(srcdir)/clustalw/util.cpp'; fi`
uninstall-info-am:

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e '1{h;s/./=/g;p;x;}' -e '$${p;x;}'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(mkdir_p) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-shar dist-tarZ dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-exec install-exec-am \
	install-info install-info-am install-man install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
