.\"                                      Hey, EMACS: -*- nroff -*-
.TH GENTLE 1 "March  9, 2010"
.SH NAME
GENtle \- program to plan genetic cloning experiments
.SH SYNOPSIS
.B gentle
.SH DESCRIPTION
GENtle integrates a series of programs and databases
to plan the integration of foreign DNA into another
larger DNA that by some means can replicate itself
or is by some other means replicated - a process
commonly referred to as
.I cloning.
.SH OPTIONS
None.
.SH ENVIRONMENT

.TP
.B GENTLE_HOMEDIR
The directory in which all the GENtle-associated files are expected, should be set to /usr/share/gentle in UNIX environments.

.SH SEE ALSO
.BR http://gentle.magnusmanske.de
.SH AUTHOR
GENtle was written by Magnus Manske.
.PP
This manual page was written by Steffen Moeller <moeller@debian.org>.

